language: node_js

node_js:
- '6'

addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
        
install:
- npm install

script: true

before_deploy:
- cat .netrc >> $HOME/.netrc
- chmod 0600 /home/travis/.netrc
- heroku apps
- heroku apps | grep -q azci-$TRAVIS_BRANCH || heroku apps:create [app-prefix]-$TRAVIS_BRANCH
- heroku git:remote -a azci-$TRAVIS_BRANCH

deploy:
  provider: heroku
  api_key: 1d8321cd-a898-4cbb-8283-6b201363c519
  app: azci-$TRAVIS_BRANCH
  on: $TRAVIS_BRANCH

after_deploy:
- ./node_modules/.bin/wdio wdio.conf || travis_terminate 1
